#!/usr/bin/with-contenv bash

checkChiaNode() {
  ps aux | grep chia_daemo[n] > /dev/null
  return $?
}

if [checkChiaNode]; then
  s6-svc -d /var/run/s6/services/chia
  chiaPID="$(pgrep chia_daemo[n])"
  kill ${chiaPID}
else
  s6-svscanctl -t /var/run/s6/services/chia
fi

while [checkChiaNode -eq 0]; do
  sleep 0.1
done
