#!/usr/bin/with-contenv bash


# environment variables
TAIL_DEBUG_LOGS=${TAIL_DEBUG_LOGS:-false}


# shutdown trap
_term() {
  echo "Caught SIGTERM signal!"
  s6-setuidgid abc /chia-blockchain/venv/bin/chia stop -d all 2>/dev/null
}
trap _term SIGTERM


# activate chia-blockchain venv
cd /chia-blockchain ; . ./activate


# run chia daemons
if [[ ${FULL_NODE} == 'true' ]]
then
  # start full-node
  s6-setuidgid abc /chia-blockchain/venv/bin/chia start farmer
elif [[ ${FARMER_ONLY} == 'true' || ${HARVESTER_ONLY} == 'true' || ${NODE_ONLY} == 'true' ]]
  # start farmer-only
  if [[ ${FARMER_ONLY} == 'true' ]]
  then
    s6-setuidgid abc /chia-blockchain/venv/bin/chia start farmer-only
  fi
  # start harvester
  if [[ ${HARVESTER_ONLY} == 'true' ]]
  then
    s6-setuidgid abc /chia-blockchain/venv/bin/chia start harvester
  fi
  # start node-only
  if [[ ${NODE_ONLY} == 'true' ]]
  then
    s6-setuidgid abc /chia-blockchain/venv/bin/chia start node
  fi
else
  echo "ERROR: invalid configuration - enable at least one service or run a full node"
  exit
fi


# run loop
while true
do
  if [[ ${TAIL_DEBUG_LOGS} == 'true' ]]; then
    tail -F /config/.chia/mainnet/log/debug.log
  else
    sleep 30
  fi
done
